# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name:  B站5000粉抽奖


on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天00:00触发

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BILI_COOKIE: ${{ secrets.BILI_COOKIE }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4    
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Run Application and Save Results
      run: dotnet run --project BiliReactionRoll/BiliReactionRoll.csproj > result.txt
    
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: roll-results
        path: result.txt
        retention-days: 5
